exports.cities = [
  { name: "Kathmandu", value: "kathmandu" },
  { name: "Pokhara", value: "pokhara" },
  { name: "Lalitpur", value: "lalitpur" },
  { name: "Biratnagar", value: "biratnagar" },
  { name: "Bharatpur", value: "bharatpur" },
  { name: "Birgunj", value: "birgunj" },
  { name: "Dharan", value: "dharan" },
  { name: "Butwal", value: "butwal" },
  { name: "Bhaktapur", value: "bhaktapur" },
  { name: "Hetauda", value: "hetauda" },
  { name: "Janakpur", value: "janakpur" },
  { name: "Itahari", value: "itahari" },
  { name: "Nepalgunj", value: "nepalgunj" },
  { name: "Ghorahi", value: "ghorahi" },
  { name: "Tulsipur", value: "tulsipur" },
  { name: "Kalaiya", value: "kalaiya" },
  { name: "Dhangadhi", value: "dhangadhi" },
  { name: "Dhankuta", value: "dhankuta" },
  { name: "Putalibazar", value: "putalibazar" },
  { name: "Mechinagar", value: "mechinagar" },
  { name: "Triyuga", value: "triyuga" },
  { name: "Gorkha", value: "gorkha" },
  { name: "Baglung", value: "baglung" },
  { name: "Tansen", value: "tansen" },
  { name: "Bhadrapur", value: "bhadrapur" },
  { name: "Rajbiraj", value: "rajbiraj" },
  { name: "Lahan", value: "lahan" },
  { name: "Gaighat", value: "gaighat" },
  { name: "Kirtipur", value: "kirtipur" },
  { name: "Siddharthanagar", value: "siddharthanagar" },
  { name: "Damak", value: "damak" },
  { name: "Suryabinayak", value: "suryabinayak" },
  { name: "Bhimeshwor", value: "bhimeshwor" },
  { name: "Ilam", value: "ilam" },
  { name: "Inaruwa", value: "inaruwa" },
  { name: "Jaleshwor", value: "jaleshwor" },
  { name: "Khandbari", value: "khandbari" },
  { name: "Mahendranagar", value: "mahendranagar" },
  { name: "Malangwa", value: "malangwa" },
  { name: "Nuwakot", value: "nuwakot" },
  { name: "Phidim", value: "phidim" },
  { name: "Ramechhap", value: "ramechhap" },
  { name: "Sandhikharka", value: "sandhikharka" },
  { name: "Sindhuli", value: "sindhuli" },
  { name: "Tikapur", value: "tikapur" },
  { name: "Waling", value: "waling" },
  { name: "Kohalpur", value: "kohalpur" },
  { name: "Gulariya", value: "gulariya" },
  { name: "Salyan", value: "salyan" },
  { name: "Rolpa", value: "rolpa" },
  { name: "Bardibas", value: "bardibas" },
  { name: "Dhulikhel", value: "dhulikhel" },
  { name: "Banepa", value: "banepa" },
  { name: "Charikot", value: "charikot" },
  { name: "Diktel", value: "diktel" },
  { name: "Sindhulimadi", value: "sindhulimadi" },
  { name: "Panauti", value: "panauti" },
  { name: "Madhyapur Thimi", value: "madhyapur-thimi" },
  { name: "Gokarneshwor", value: "gokarneshwor" },
  { name: "Shankharapur", value: "shankharapur" },
  { name: "Tokha", value: "tokha" },
  { name: "Tarakeshwar", value: "tarakeshwar" },
  { name: "Budhanilkantha", value: "budhanilkantha" },
  { name: "Nagarjun", value: "nagarjun" },
  { name: "Chandragiri", value: "chandragiri" },
  { name: "Dakshinkali", value: "dakshinkali" },
  { name: "Chitwan", value: "chitwan" },
  { name: "Makwanpur", value: "makwanpur" },
  { name: "Rautahat", value: "rautahat" },
  { name: "Bara", value: "bara" },
  { name: "Parsa", value: "parsa" },
  { name: "Rupandehi", value: "rupandehi" },
  { name: "Kapilvastu", value: "kapilvastu" },
  { name: "Arghakhanchi", value: "arghakhanchi" },
  { name: "Pyuthan", value: "pyuthan" },
  { name: "Rukum", value: "rukum" },
  { name: "Dang", value: "dang" },
  { name: "Surkhet", value: "surkhet" },
  { name: "Banke", value: "banke" },
  { name: "Bardiya", value: "bardiya" },
  { name: "Dailekh", value: "dailekh" },
  { name: "Jajarkot", value: "jajarkot" },
  { name: "Dolpa", value: "dolpa" },
  { name: "Jumla", value: "jumla" },
  { name: "Kalikot", value: "kalikot" },
  { name: "Mugu", value: "mugu" },
  { name: "Humla", value: "humla" },
  { name: "Bajura", value: "bajura" },
  { name: "Bajhang", value: "bajhang" },
  { name: "Achham", value: "achham" },
  { name: "Doti", value: "doti" },
  { name: "Kailali", value: "kailali" },
  { name: "Kanchanpur", value: "kanchanpur" },
  { name: "Dadeldhura", value: "dadeldhura" },
  { name: "Baitadi", value: "baitadi" },
  { name: "Darchula", value: "darchula" },
];

exports.busPark = [
  { name: "Gongabu Bus Park", value: "gongabu-bus-park" },
  { name: "Ratnapark Bus Park", value: "ratnapark-bus-park" },
  { name: "Kalanki Bus Park", value: "kalanki-bus-park" },
  { name: "Koteshwor Bus Park", value: "koteshwor-bus-park" },
  { name: "Chabahil Bus Park", value: "chabahil-bus-park" },
  { name: "Lagankhel Bus Park", value: "lagankhel-bus-park" },
  { name: "Patan Bus Park", value: "patan-bus-park" },
  { name: "Bhaktapur Bus Park", value: "bhaktapur-bus-park" },
  { name: "Banepa Bus Park", value: "banepa-bus-park" },
  { name: "Dhulikhel Bus Park", value: "dhulikhel-bus-park" },
  { name: "Kalimati Bus Park", value: "kalimati-bus-park" },
  { name: "Pulchowk Bus Park", value: "pulchowk-bus-park" },
  { name: "New Bus Park", value: "new-bus-park" },
  { name: "Sundhara Bus Park", value: "sundhara-bus-park" },
  { name: "Gaushala Bus Park", value: "gaushala-bus-park" },
  { name: "Jorpati Bus Park", value: "jorpati-bus-park" },
  { name: "Balaju Bus Park", value: "balaju-bus-park" },
  { name: "Thamel Bus Park", value: "thamel-bus-park" },
  { name: "Sankhamul Bus Park", value: "sankhamul-bus-park" },
  { name: "Suryabinayak Bus Park", value: "suryabinayak-bus-park" },
  { name: "Kirtipur Bus Park", value: "kirtipur-bus-park" },
  { name: "Satdobato Bus Park", value: "satdobato-bus-park" },
  { name: "Chitwan Bus Park", value: "chitwan-bus-park" },
  { name: "Pokhara Bus Park", value: "pokhara-bus-park" },
  { name: "Damauli Bus Park", value: "damauli-bus-park" },
  { name: "Gorkha Bus Park", value: "gorkha-bus-park" },
  { name: "Narayanghat Bus Park", value: "narayanghat-bus-park" },
  { name: "Bharatpur Bus Park", value: "bharatpur-bus-park" },
  { name: "Butwal Bus Park", value: "butwal-bus-park" },
  { name: "Lumbini Bus Park", value: "lumbini-bus-park" },
  { name: "Palpa Bus Park", value: "palpa-bus-park" },
  { name: "Ghorahi Bus Park", value: "ghorahi-bus-park" },
  { name: "Nepalgunj Bus Park", value: "nepalgunj-bus-park" },
  { name: "Dhangadhi Bus Park", value: "dhangadhi-bus-park" },
  { name: "Biratnagar Bus Park", value: "biratnagar-bus-park" },
  { name: "Dharan Bus Park", value: "dharan-bus-park" },
  { name: "Ilam Bus Park", value: "ilam-bus-park" },
  { name: "Janakpur Bus Park", value: "janakpur-bus-park" },
  { name: "Lahan Bus Park", value: "lahan-bus-park" },
  { name: "Birgunj Bus Park", value: "birgunj-bus-park" },
  { name: "Hetauda Bus Park", value: "hetauda-bus-park" },
  { name: "Malangawa Bus Park", value: "malangawa-bus-park" },
  { name: "Rajbiraj Bus Park", value: "rajbiraj-bus-park" },
  { name: "Simara Bus Park", value: "simara-bus-park" },
  { name: "Tulsipur Bus Park", value: "tulsipur-bus-park" },
  { name: "Lamahi Bus Park", value: "lamahi-bus-park" },
  { name: "Sandhikharka Bus Park", value: "sandhikharka-bus-park" },
  { name: "Waling Bus Park", value: "waling-bus-park" },
  { name: "Besisahar Bus Park", value: "besisahar-bus-park" },
  { name: "Bhaktapur Bus Park", value: "bhaktapur-bus-park" },
  { name: "Putalisadak Bus Park", value: "putalisadak-bus-park" },
  { name: "Sanepa Bus Park", value: "sanepa-bus-park" },
  { name: "Damauli Bus Park", value: "damauli-bus-park" },
  { name: "Birendranagar Bus Park", value: "birendranagar-bus-park" },
  { name: "Khandbari Bus Park", value: "khandbari-bus-park" },
  { name: "Madhyapur Thimi Bus Park", value: "madhyapur-thimi-bus-park" },
  { name: "Tikapur Bus Park", value: "tikapur-bus-park" },
];

exports.states = [
  {
    name: "Province No. 1",
    value: "province_no_1",
  },
  {
    name: "Province No. 2",
    value: "province_no_2",
  },
  {
    name: "Bagmati Province",
    value: "bagmati_province",
  },
  {
    name: "Gandaki Province",
    value: "gandaki_province",
  },
  {
    name: "Lumbini Province",
    value: "lumbini_province",
  },
  {
    name: "Karnali Province",
    value: "karnali_province",
  },
  {
    name: "Sudurpashchim Province",
    value: "sudurpashchim_province",
  },
];
